"""empty message

Revision ID: 87eb6f41ec2b
Revises: 
Create Date: 2020-04-19 21:47:06.577957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87eb6f41ec2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hanzi', sa.String(length=10), nullable=False),
    sa.Column('pinyin', sa.String(length=50), nullable=False),
    sa.Column('english', sa.String(length=50), nullable=False),
    sa.Column('book_volume', sa.Integer(), nullable=False),
    sa.Column('character_set', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
